import os
import csv
import shutil
from pathlib import Path
from unittest.mock import patch, MagicMock, mock_open
from typing import List
import pytest
from ion_CSP.gen_opt import CrystalGenerator


# ==================== 帮助函数：创建模拟的离子组分文件 ====================
def create_ion_files(tmp_path: Path) -> List[Path]:
    """创建模拟的离子结构文件（如 N2H6.gjf 与 N5.gjf）"""
    ion_files = []
    path1, path2 = tmp_path / "N2H6.gjf", tmp_path / "N5.gjf"
    path1.write_text(
            r"""%chk=GISYIR.chk
#P B3LYP/6-31G*

Generated by Multiwfn

  2  1
N      0.73082600   -0.07120700   -0.03991000
N     -0.73082700    0.07120700    0.03991000
H      0.98863400   -1.06315900   -0.23934100
H      1.11329300    0.53155800   -0.80188100
H      1.17309100    0.21250300    0.86237400
H     -1.17309200   -0.21250300   -0.86237400
H     -1.11329400   -0.53155800    0.80188100
H     -0.98863400    1.06315900    0.23934100

""",
            encoding="utf-8",
        )
    ion_files.append(path1)
    path2.write_text(r"""%chk=N5.chk
#P B3LYP/6-31G*

Generated by Multiwfn

 -1  1
N      5.68107100   -0.02073700    5.05520300
N      5.75024300   -1.54374400    6.57460400
N      4.99576900   -0.58483300    6.04587900
N      6.86056300   -0.63037300    4.97316600
N      6.90312600   -1.57214500    5.91086700
 
""")
    ion_files.append(path2)
    return ion_files


# ==================== 常量配置 ====================
SAMPLE_SPECIES = ["N2H6.gjf", "N5.gjf"]
SAMPLE_ION_NUMBERS = [1, 2]
SAMPLE_CELL_ATOMS = 18  # (8 atoms in N2H6) * 1 + (5 atoms in N5) * 2 = 18


# ==================== pytest fixture: 创建干净测试环境 ====================
@pytest.fixture
def crystal_generator(tmp_path: Path):
    """
    创建一个干净的 CrystalGenerator 实例，自动构建目录结构和模拟文件。
    """
    # 创建模拟的离子组分文件
    ion_files = create_ion_files(tmp_path)

    # 创建模拟的 mlp_opt.py 和 model.pt（模拟 importlib.resources）
    mlp_opt_file = tmp_path / "mlp_opt.py"
    mlp_opt_file.write_text("print('MLP optimization script')", encoding="utf-8")

    model_file = tmp_path / "model.pt"
    model_file.write_text("dummy model content", encoding="utf-8")

    # 创建一个 mock 的 importlib.resources.files
    with patch("importlib.resources.files") as mock_resources:
        # 模拟 mlp_opt.py 和 model.pt 的路径
        mock_resources.side_effect = (
            lambda pkg: tmp_path if pkg == "ion_CSP" else tmp_path / "model"
        )

        # 创建 CrystalGenerator 实例
        cg = CrystalGenerator(
            work_dir=str(tmp_path),
            ion_numbers=SAMPLE_ION_NUMBERS,
            species=SAMPLE_SPECIES,
        )

        # 确保目录已创建
        assert cg.generation_dir.exists()
        assert cg.POSCAR_dir.exists()
        assert cg.primitive_cell_dir.exists()

        # 模拟 pyxtal 生成的 POSCAR 文件（用于后续测试）
        os.makedirs(cg.POSCAR_dir, exist_ok=True)
        for i in range(5):
            (cg.POSCAR_dir / f"POSCAR_{i}").write_text("dummy POSCAR", encoding="utf-8")

        # 模拟 group_counts
        cg.group_counts = [1, 2, 1, 1]  # 4 个空间群，分别生成 1,2,1,1 个结构

        yield cg

        # 清理
        if cg.generation_dir.exists():
            shutil.rmtree(cg.generation_dir, ignore_errors=True)


# ==================== 测试 __init__ ====================
def test_crystal_generator_init(crystal_generator: CrystalGenerator, tmp_path: Path):
    """测试初始化逻辑"""
    cg = crystal_generator
    assert cg.base_dir == str(tmp_path)
    assert cg.ion_numbers == [2, 1]
    assert cg.species == ["NaCl.json", "KBr.json"]
    assert len(cg.species_paths) == 2
    assert cg.cell_atoms == 6
    assert cg.generation_dir.exists()
    assert cg.POSCAR_dir.exists()
    assert cg.primitive_cell_dir.exists()


# ==================== 测试 _sequentially_read_files ====================
def test_sequentially_read_files_success(crystal_generator: CrystalGenerator):
    """测试文件按数字顺序正确排序"""
    files = crystal_generator._sequentially_read_files(
        crystal_generator.POSCAR_dir, prefix_name="POSCAR_"
    )
    assert len(files) == 5
    assert files[0] == (0, "POSCAR_0")
    assert files[-1] == (4, "POSCAR_4")


def test_sequentially_read_files_invalid_name(crystal_generator: CrystalGenerator):
    """测试非法文件名（非数字后缀）被过滤"""
    (crystal_generator.POSCAR_dir / "POSCAR_xxx").touch()
    files = crystal_generator._sequentially_read_files(
        crystal_generator.POSCAR_dir, prefix_name="POSCAR_"
    )
    assert len(files) == 5  # xxx 被过滤
    assert "POSCAR_xxx" not in [f[1] for f in files]


# ==================== 测试 generate_structures ====================
@patch("pyxtal.pyxtal")
@patch("os.makedirs")
def test_generate_structures_success(
    mock_makedirs, mock_pyxtal, crystal_generator: CrystalGenerator, tmp_path: Path
):
    """测试结构生成成功路径"""
    # 模拟 pyxtal 成功生成
    mock_structure = MagicMock()
    mock_structure.to_file = MagicMock()
    mock_pyxtal.return_value = mock_structure

    # 模拟生成 5 个结构，分布在 2 个空间群
    mock_structure.from_random.side_effect = [None, None, None, None, None]

    # 模拟异常不触发
    with patch("logging.info") as mock_log:
        crystal_generator.generate_structures(num_per_group=5, space_groups_limit=2)

    # 验证
    assert mock_pyxtal.call_count == 5
    assert mock_structure.from_random.call_count == 5
    assert mock_structure.to_file.call_count == 5

    # 验证 CSV 文件
    csv_path = tmp_path / "1_generated" / "generation.csv"
    assert csv_path.exists()
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        rows = list(reader)
    assert rows[0] == ["Space_group", "POSCAR_num", "Bad_num", "Exception"]
    assert rows[1] == ["1", "5", "0", "None"]  # 只有第一个空间群被用（limit=2）
    assert len(rows) == 3  # 空间群 1 和 2

    # 验证日志
    mock_log.assert_any_call(
        "Using pyxtal.from_random, 5 ion crystal structures were randomly generated"
    )


@patch("pyxtal.pyxtal")
@patch("os.makedirs")
def test_generate_structures_compatability_error(
    mock_makedirs, mock_pyxtal, crystal_generator: CrystalGenerator, tmp_path: Path
):
    """测试生成时出现 Comp_CompatibilityError，跳过当前空间群"""
    mock_structure = MagicMock()
    mock_structure.to_file = MagicMock()
    mock_pyxtal.return_value = mock_structure

    # 第一个结构成功，第二个触发异常
    def side_effect(*args, **kwargs):
        if mock_structure.from_random.call_count == 1:
            return None
        else:
            raise Exception("Comp_CompatibilityError")  # 模拟异常

    mock_structure.from_random.side_effect = side_effect

    with patch("logging.info") as mock_log:
        crystal_generator.generate_structures(num_per_group=5, space_groups_limit=1)

    # 验证 CSV
    csv_path = tmp_path / "1_generated" / "generation.csv"
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        rows = list(reader)
    assert rows[1][2] == "0"  # Bad_num 仍为 0
    assert rows[1][3] == "Comp_CompatibilityError"

    # 验证只生成了 1 个结构
    assert mock_structure.from_random.call_count == 1


# ==================== 测试 _single_phonopy_processing ====================
@patch("subprocess.run")
@patch("ase.io.read")
@patch("shutil.copy")
@patch("shutil.move")
@patch("os.remove")
def test_single_phonopy_processing_success(
    mock_remove,
    mock_move,
    mock_copy,
    mock_read,
    mock_run,
    crystal_generator: CrystalGenerator,
    tmp_path: Path,
):
    """测试 phonopy 处理成功路径"""
    mock_run.return_value.returncode = 0
    mock_read.return_value = MagicMock()  # 原子数匹配
    mock_read.return_value.get_number_of_atoms.return_value = (
        crystal_generator.cell_atoms
    )

    # 模拟文件存在
    (crystal_generator.POSCAR_dir / "POSCAR_0").write_text("dummy", encoding="utf-8")
    (crystal_generator.primitive_cell_dir).mkdir(exist_ok=True)

    crystal_generator._single_phonopy_processing("POSCAR_0")

    # 验证
    mock_copy.assert_called_once_with(
        str(crystal_generator.POSCAR_dir / "POSCAR_0"),
        str(crystal_generator.POSCAR_dir / "POSCAR"),
    )
    mock_run.assert_called_once()
    mock_move.assert_called_once_with(
        str(crystal_generator.POSCAR_dir / "PPOSCAR"),
        str(crystal_generator.primitive_cell_dir / "POSCAR_0"),
    )
    mock_read.assert_called_once()
    assert not mock_remove.called  # 没有删除，因为原子数匹配


@patch("subprocess.run")
@patch("ase.io.read")
@patch("shutil.copy")
@patch("shutil.move")
@patch("os.remove")
@patch("builtins.open", new_callable=mock_open)
def test_single_phonopy_processing_atom_mismatch(
    mock_open_file,
    mock_remove,
    mock_move,
    mock_copy,
    mock_read,
    mock_run,
    crystal_generator: CrystalGenerator,
    tmp_path: Path,
):
    """测试原子数不匹配，删除文件并更新 CSV"""
    mock_run.return_value.returncode = 0
    mock_read.return_value = MagicMock()
    mock_read.return_value.get_number_of_atoms.return_value = 100  # 不匹配

    (crystal_generator.POSCAR_dir / "POSCAR_0").write_text("dummy", encoding="utf-8")
    (crystal_generator.primitive_cell_dir).mkdir(exist_ok=True)

    # 创建初始 CSV
    csv_path = tmp_path / "1_generated" / "generation.csv"
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Space_group", "POSCAR_num", "Bad_num", "Exception"])
        writer.writerow([1, 1, 0, "None"])

    crystal_generator._single_phonopy_processing("POSCAR_0")

    # 验证文件被删除
    mock_remove.assert_called_once_with(
        str(crystal_generator.primitive_cell_dir / "POSCAR_0")
    )

    # 验证 CSV 被更新
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        rows = list(reader)
    assert rows[1][2] == "1"  # Bad_num 增加
    assert rows[1][3] == "AtomNumberError"


# ==================== 测试 _find_space_group ====================
def test_find_space_group_success(crystal_generator: CrystalGenerator):
    """测试空间群查找成功"""
    assert crystal_generator._find_space_group(0) == 1
    assert crystal_generator._find_space_group(1) == 2
    assert crystal_generator._find_space_group(2) == 2
    assert crystal_generator._find_space_group(3) == 3
    assert crystal_generator._find_space_group(4) == 4


def test_find_space_group_not_found(crystal_generator: CrystalGenerator):
    """测试找不到空间群"""
    with pytest.raises(ValueError, match="POSCAR 99 not found"):
        crystal_generator._find_space_group(99)


# ==================== 测试 phonopy_processing ====================
@patch("os.chdir")
@patch("shutil.rmtree")
@patch("os.makedirs")
@patch("logging.info")
def test_phonopy_processing_success(
    mock_log,
    mock_makedirs,
    mock_rmtree,
    mock_chdir,
    crystal_generator: CrystalGenerator,
    tmp_path: Path,
):
    """测试 phonopy_processing 成功路径"""
    # 创建 POSCAR 文件
    for i in range(3):
        (crystal_generator.POSCAR_dir / f"POSCAR_{i}").write_text(
            "dummy", encoding="utf-8"
        )

    with patch(
        "ion_CSP.crystal_generator.CrystalGenerator._single_phonopy_processing"
    ) as mock_single:
        crystal_generator.phonopy_processing()

    # 验证
    mock_chdir.assert_called_once_with(str(crystal_generator.POSCAR_dir))
    assert mock_single.call_count == 3
    mock_rmtree.assert_called_once_with(str(crystal_generator.POSCAR_dir))
    mock_log.assert_any_call("The phonopy processing has been completed!!")


@patch("os.chdir")
@patch("shutil.rmtree")
@patch("os.makedirs")
def test_phonopy_processing_no_files(
    mock_makedirs,
    mock_rmtree,
    mock_chdir,
    crystal_generator: CrystalGenerator,
    tmp_path: Path,
):
    """测试没有 POSCAR 文件时抛出异常"""
    # 不创建任何 POSCAR 文件
    with pytest.raises(
        FileNotFoundError, match="There are no POSCAR structure files after generating"
    ):
        crystal_generator.phonopy_processing()


# ==================== 测试 dpdisp_mlp_tasks ====================
@patch("dpdispatcher.Machine.load_from_json")
@patch("dpdispatcher.Resources.load_from_json")
@patch("os.chdir")
@patch("shutil.copy")
@patch("shutil.rmtree")
@patch("os.makedirs")
@patch("os.remove")
@patch("os.environ")
@patch("subprocess.check_output")
@patch("time.sleep")
def test_dpdisp_mlp_tasks_local_gpu(
    mock_sleep,
    mock_check_output,
    mock_environ,
    mock_remove,
    mock_makedirs,
    mock_rmtree,
    mock_copy,
    mock_chdir,
    mock_load_resources,
    mock_load_machine,
    crystal_generator: CrystalGenerator,
    tmp_path: Path,
):
    """测试本地 GPU 模式"""
    # 模拟 GPU 可用
    mock_check_output.return_value = (
        "0,10,1024\n1,20,1024\n2,50,1024\n"  # GPU 0,1,2，内存占用 10%,20%,50%
    )
    mock_load_machine.return_value.serialize.return_value = {
        "context_type": "LocalContext",
        "batch_type": "Shell",
    }
    mock_load_resources.return_value.serialize.return_value = {
        "number_node": 1,
        "cpu_per_node": 4,
        "gpu_per_node": 1,
    }

    # 创建文件
    for i in range(4):
        (crystal_generator.primitive_cell_dir / f"POSCAR_{i}").write_text(
            "dummy", encoding="utf-8"
        )

    # 模拟任务分发
    crystal_generator.dpdisp_mlp_tasks(
        machine=str(tmp_path / "machine.json"),
        resources=str(tmp_path / "resources.json"),
        nodes=2,
    )

    # 验证
    mock_check_output.assert_called_once()
    mock_environ.__setitem__.assert_called_once_with("CUDA_VISIBLE_DEVICES", "0")
    mock_chdir.assert_called_once_with(str(crystal_generator.primitive_cell_dir))

    # 验证复制了文件
    mock_copy.assert_any_call(
        str(crystal_generator.mlp_opt_file),
        str(crystal_generator.primitive_cell_dir / "mlp_opt.py"),
    )
    mock_copy.assert_any_call(
        str(crystal_generator.model_file),
        str(crystal_generator.primitive_cell_dir / "model.pt"),
    )

    # 验证 task_list 创建
    # 4 个文件，2 个节点 → [0,2], [1,3]
    # 每个节点有 2 个 forward_files + 2 个 backward_files + 2 个 POSCAR
    # 验证提交了 2 个 task
    # （dpdispatcher 的 Task/Submission 会被 mock，但调用次数应为 2）

    # 验证清理
    mock_remove.assert_any_call(
        str(crystal_generator.primitive_cell_dir / "mlp_opt.py")
    )
    mock_remove.assert_any_call(str(crystal_generator.primitive_cell_dir / "model.pt"))
    mock_rmtree.assert_called()  # 至少调用了一次 pop{n} 目录


@patch("dpdispatcher.Machine.load_from_json")
@patch("dpdispatcher.Resources.load_from_json")
@patch("os.chdir")
@patch("shutil.copy")
@patch("shutil.rmtree")
@patch("os.makedirs")
@patch("os.remove")
@patch("os.environ")
def test_dpdisp_mlp_tasks_remote(
    mock_environ,
    mock_remove,
    mock_makedirs,
    mock_rmtree,
    mock_copy,
    mock_chdir,
    mock_load_resources,
    mock_load_machine,
    crystal_generator: CrystalGenerator,
    tmp_path: Path,
):
    """测试远程 SSH 模式"""
    mock_load_machine.return_value.serialize.return_value = {
        "context_type": "SSHContext",
        "batch_type": "Shell",
    }
    mock_load_resources.return_value.serialize.return_value = {
        "number_node": 1,
        "cpu_per_node": 4,
        "gpu_per_node": 0,
    }

    for i in range(3):
        (crystal_generator.primitive_cell_dir / f"POSCAR_{i}").write_text(
            "dummy", encoding="utf-8"
        )

    crystal_generator.dpdisp_mlp_tasks(
        machine=str(tmp_path / "machine.json"),
        resources=str(tmp_path / "resources.json"),
        nodes=1,
    )

    # 验证没有设置 CUDA_VISIBLE_DEVICES
    mock_environ.__setitem__.assert_not_called()

    # 验证 parent = "data/"
    # 验证删除了 data/ 目录
    mock_rmtree.assert_any_call(str(crystal_generator.primitive_cell_dir / "data"))


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--cov=ion_CSP.read_mlp_density"])