convert_SMILES:
  charge_screen: -1
  csv_file: ions.csv
  group_name: nitro
  group_screen: '[N+](=O)[O-]'
  group_screen_invert: false
  machine: /your/cpu/machine/config/path
  nodes: 2
  resources: /your/cpu/resources/config/path
  screen: true
empirical_estimate:
  folders:
  - charge_2
  - charge_-1
  ion_numbers:
  - 2
  - 4
  make_combo_dir: true
  num_combos: 20
  ratios:
  - 1
  - 2
gen_opt:
  ion_numbers:
  - 2
  - 4
  machine: /your/gpu/machine/config/path
  nodes: 1
  num_per_group: 10
  resources: /your/gpu/resources/config/path
  space_groups_limit: 15
  species:
  - ACEGUL.gjf
  - AGIDOM.gjf
read_mlp_density:
  detail_log: false
  molecules_screen: true
  n_screen: 2
vasp_processing:
  machine: /your/cpu/machine/config/path
  molecules_prior: true
  nodes: 2
  resources: /your/cpu/resources/config/path
