import os
import pytest
import logging
import numpy as np
from ase import Atoms
from unittest.mock import MagicMock

from ion_CSP.identify_molecules import (
    identify_molecules,
    format_molecule_output,
    molecules_information,
)

# 配置日志
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")


def create_gjf_file(path: str, filename: str, atoms: Atoms):
    """手动创建临时的GJF文件"""
    filepath = os.path.join(path, filename)
    with open(filepath, "w") as f:
        f.write("#N\n\n")  # Gaussian 文件头
        f.write("Generated by ASE test\n\n")
        f.write("0 1\n")
        for atom in atoms:
            f.write(f"{atom.symbol} {atom.x} {atom.y} {atom.z}\n")
        f.write("\n\n")  # 文件结束
    return filepath


@pytest.fixture
def setup_test_environment(tmp_path):
    """设置测试环境，创建临时目录并切换工作目录"""
    os.chdir(tmp_path)
    return tmp_path


# ==================== 测试 identify_molecules 函数正确识别 ====================
def test_identify_molecules_single_water_molecule(setup_test_environment):
    """测试单个水分子"""
    # 创建初始GJF文件
    water = Atoms("OH2", positions=[[0, 0, 0], [1, 0, 0], [0, 1, 0]])
    create_gjf_file(setup_test_environment, "water.gjf", water)

    # 运行识别函数
    merged_molecules, molecules_flag, initial_info = identify_molecules(water)

    # 验证结果
    expected_molecule = frozenset([("O", 1), ("H", 2)])
    assert len(merged_molecules) == 1
    assert expected_molecule in merged_molecules
    assert merged_molecules[expected_molecule] == 1
    assert molecules_flag is True
    assert initial_info == [{"O": 1, "H": 2}]


def test_identify_molecules_two_isolated_water_molecules(setup_test_environment):
    """测试两个独立的水分子"""
    # 创建两个初始GJF文件
    water1 = Atoms("OH2", positions=[[0, 0, 0], [1, 0, 0], [0, 1, 0]])
    water2 = Atoms("OH2", positions=[[10, 0, 0], [11, 0, 0], [10, 1, 0]])
    create_gjf_file(setup_test_environment, "water1.gjf", water1)
    create_gjf_file(setup_test_environment, "water2.gjf", water2)

    # 合并两个分子
    combined = water1 + water2

    # 运行识别函数
    merged_molecules, molecules_flag, initial_info = identify_molecules(combined)

    # 验证结果
    expected_molecule = frozenset([("O", 1), ("H", 2)])
    assert len(merged_molecules) == 1
    assert expected_molecule in merged_molecules
    assert merged_molecules[expected_molecule] == 2
    assert molecules_flag is True


def test_identify_molecules_water_and_methane_molecules(setup_test_environment):
    """测试水分子和甲烷分子"""
    # 创建初始GJF文件
    water = Atoms("OH2", positions=[[0, 0, 0], [1, 0, 0], [0, 1, 0]])
    methane = Atoms(
        "CH4", positions=[[10, 0, 0], [11, 0, 0], [10, 1, 0], [10, 0, 1], [9, 0, 0]]
    )
    create_gjf_file(setup_test_environment, "water.gjf", water)
    create_gjf_file(setup_test_environment, "methane.gjf", methane)

    # 合并两个分子
    combined = water + methane

    # 运行识别函数
    merged_molecules, molecules_flag, initial_info = identify_molecules(combined)

    # 验证结果
    water_mol = frozenset([("O", 1), ("H", 2)])
    methane_mol = frozenset([("C", 1), ("H", 4)])

    assert len(merged_molecules) == 2
    assert water_mol in merged_molecules
    assert methane_mol in merged_molecules
    assert merged_molecules[water_mol] == 1
    assert merged_molecules[methane_mol] == 1
    assert molecules_flag is True
    assert sorted(initial_info, key=lambda x: sorted(x.items())) == sorted(
        [{"O": 1, "H": 2}, {"C": 1, "H": 4}], key=lambda x: sorted(x.items())
    )


# ==================== 测试 identify_molecules 函数异常处理 ====================
def test_identify_molecules_mismatched_molecules(setup_test_environment):
    """测试分子不匹配的情况"""
    # 只创建一个初始GJF文件
    water = Atoms("OH2", positions=[[0, 0, 0], [1, 0, 0], [0, 1, 0]])
    create_gjf_file(setup_test_environment, "water.gjf", water)

    # 创建两个独立的水分子
    water1 = Atoms("OH", positions=[[0, 0, 0], [1, 0, 0]])
    water2 = Atoms("OH3", positions=[[10, 0, 0], [11, 0, 0], [10, 1, 0], [10, 1, 1]])
    combined = water1 + water2

    # 运行识别函数
    merged_molecules, molecules_flag, initial_info = identify_molecules(combined)

    # 验证结果
    expected_molecule = frozenset([("O", 1), ("H", 2)])
    assert len(merged_molecules) == 3
    # A fragment can retain the same formula as the expected molecule, but the
    # complete graph multiset and multiplicity must still fail.
    assert merged_molecules[expected_molecule] == 1
    assert molecules_flag is False
    assert initial_info == [{"O": 1, "H": 2}]


def test_identify_molecules_no_gjf_files(setup_test_environment):
    """测试没有GJF文件的情况"""
    water = Atoms("OH2", positions=[[0, 0, 0], [1, 0, 0], [0, 1, 0]])

    # 运行识别函数
    merged_molecules, molecules_flag, initial_info = identify_molecules(water)

    # 验证结果
    expected_molecule = frozenset([("O", 1), ("H", 2)])
    assert len(merged_molecules) == 1
    assert expected_molecule in merged_molecules
    assert merged_molecules[expected_molecule] == 1
    assert molecules_flag is False  # 没有初始GJF文件
    assert initial_info == []


def test_identify_molecules_complex_bonding():
    """
    Test identification of multiple disconnected molecules and complex bonding.
    Includes:
    - Two separate molecules: H2O and CH4
    - One cyclic molecule: benzene (C6H6)
    - Ensure DFS correctly identifies 3 independent molecules
    """

    # 1. 构建一个包含三个独立分子的体系：
    #    - H2O: 3 atoms
    #    - CH4: 5 atoms
    #    - C6H6 (benzene): 12 atoms
    #    总计：20 个原子

    positions = []
    symbols = []

    # --- H2O 分子 ---
    h2o_positions = [
        [0.0, 0.0, 0.0],  # O
        [0.95, 0.0, 0.0],  # H1
        [-0.95, 0.0, 0.0],  # H2
    ]
    positions.extend(h2o_positions)
    symbols.extend(["O", "H", "H"])

    # --- CH4 分子（与 H2O 不相连）---
    ch4_positions = [
        [5.0, 0.0, 0.0],  # C
        [5.0 + 1.09, 0.0, 0.0],  # H1
        [5.0, 1.09, 0.0],  # H2
        [5.0, 0.0, 1.09],  # H3
        [5.0 - 0.545, -0.545, -0.545],  # H4 (近似四面体)
    ]
    positions.extend(ch4_positions)
    symbols.extend(["C", "H", "H", "H", "H"])

    # --- 苯环 C6H6（环状结构）---
    # 简化模型：六边形平面结构，键长 ~1.4 Å
    benzene_radius = 1.4
    for i in range(6):
        angle = i * np.pi / 3
        x = benzene_radius * np.cos(angle) + 10.0  # 平移到远处，避免与前两个分子成键
        y = benzene_radius * np.sin(angle) + 0.0
        z = 0.0
        positions.append([x, y, z])  # C
        symbols.append("C")
        # 每个 C 上加一个 H，向外径向
        h_x = x + 1.09 * np.cos(angle + np.pi / 2)
        h_y = y + 1.09 * np.sin(angle + np.pi / 2)
        h_z = 0.0
        positions.append([h_x, h_y, h_z])  # H
        symbols.append("H")

    # 创建 Atoms 对象（非周期性）
    cell = np.eye(3) * 20.0  # 20Å 足够大，无周期性成键
    atoms = Atoms(symbols=symbols, positions=positions, cell=cell, pbc=False)

    # 2. 调用函数
    molecules, flag, initial_info = identify_molecules(atoms, MagicMock())

    # 3. 验证：应识别出 3 个独立分子
    assert len(molecules) == 3, f"Expected 3 molecules, got {len(molecules)}"

    # 4. 验证每个分子的元素组成
    molecule_dicts = [dict(mol) for mol in molecules.keys()]

    # 按元素计数排序，便于比较
    molecule_dicts_sorted = sorted(
        molecule_dicts, key=lambda x: tuple(sorted(x.items()))
    )

    expected_molecules = [
        {"O": 1, "H": 2},  # H2O
        {"C": 1, "H": 4},  # CH4
        {"C": 6, "H": 6},  # C6H6
    ]
    expected_sorted = sorted(expected_molecules, key=lambda x: tuple(sorted(x.items())))

    assert molecule_dicts_sorted == expected_sorted, (
        f"Expected: {expected_sorted}\nGot: {molecule_dicts_sorted}"
    )

    # 5. 验证 flag（匹配初始文件）：我们不关心，因为 base_dir 是 MagicMock()
    assert isinstance(flag, bool)

    # 6. 验证 initial_info：应为 list[dict]，我们没提供 .gjf 文件，所以是空列表
    assert isinstance(initial_info, list)
    assert len(initial_info) == 0  # 因为 base_dir 是 MagicMock()，无 .gjf 文件


def test_identify_molecules_empty_structure():
    """
    Test that identify_molecules handles an empty Atoms object gracefully.
    Should return empty list of molecules, flag=True (empty matches empty .gjf), initial_info=[]
    """

    # 关键：创建空原子体系，但显式设置合法 cell 和 pbc
    atoms = Atoms(
        symbols=[],  # 无原子
        positions=np.zeros((0, 3)),  # 0 个位置
        cell=np.eye(3),  # 必须是 (3,3) 数组！不能是 None
        pbc=False,  # 非周期性
    )

    # 调用函数
    molecules, flag, initial_info = identify_molecules(atoms, MagicMock())

    # 验证：没有分子
    assert len(molecules) == 0, "Empty structure should return 0 molecules"

    # 验证 flag：空体系与空 .gjf 文件匹配 → 应为 True
    assert flag is True, "Empty structure should match empty initial molecules"

    # 验证 initial_info：无 .gjf 文件，应为 []
    assert isinstance(initial_info, list)
    assert len(initial_info) == 0


def test_identify_molecules_rejects_same_formula_different_topology(
    setup_test_environment,
):
    initial = Atoms(
        "N4", positions=[[0, 0, 0], [1.3, 0, 0], [2.6, 0, 0], [3.9, 0, 0]]
    )
    create_gjf_file(setup_test_environment, "N4.gjf", initial)
    observed = Atoms(
        "N4",
        positions=[[0, 0, 0], [1.3, 0, 0], [1.3, 1.3, 0], [0, 1.3, 0]],
    )

    _, flag, _ = identify_molecules(observed, setup_test_environment)

    assert flag is False


def test_identify_molecules_respects_configured_multiplicity(
    setup_test_environment,
):
    water = Atoms("OH2", positions=[[0, 0, 0], [0.95, 0, 0], [0, 0.95, 0]])
    create_gjf_file(setup_test_environment, "water.gjf", water)
    (setup_test_environment / "config.yaml").write_text(
        """gen_opt:
  species: [water.gjf]
  ion_numbers: [2]
""",
        encoding="utf-8",
    )

    _, one_flag, _ = identify_molecules(water, setup_test_environment)
    two_waters = water + Atoms(
        "OH2", positions=[[10, 0, 0], [10.95, 0, 0], [10, 0.95, 0]]
    )
    _, two_flag, _ = identify_molecules(two_waters, setup_test_environment)

    assert one_flag is False
    assert two_flag is True


# ==================== 测试 format_molecule_output 函数 ====================
def test_format_molecule_output_with_other_elements():
    """测试当分子包含非标准元素时，按字母顺序排序并正确格式化"""
    molecule_dict = {"C": 2, "H": 6, "O": 1, "S": 1, "Cl": 2}
    formatted_output, total_atoms = format_molecule_output(molecule_dict)
    assert formatted_output == "C2O1H6Cl2S1"
    assert total_atoms == 12


# ==================== 测试 molecules_information 函数 ====================
def test_molecules_information_logging(caplog):
    """测试分子信息日志输出"""
    # 准备测试数据
    molecules = {frozenset([("C", 1), ("H", 4)]): 1, frozenset([("O", 1), ("H", 2)]): 2}
    molecules_flag = True
    initial_info = [{"C": 1, "H": 4}, {"O": 1, "H": 2}]

    # 运行信息输出函数
    with caplog.at_level(logging.INFO):
        molecules_information(molecules, molecules_flag, initial_info)

    # 验证日志输出
    assert "Initial molecules:" in caplog.text
    assert "Molecule 1 (Total Atoms: 5): C1H4" in caplog.text
    assert "Molecule 2 (Total Atoms: 3): O1H2" in caplog.text
    assert "Molecule 1 (Total Atoms: 5, Count: 1): C1H4" in caplog.text
    assert "Molecule 2 (Total Atoms: 3, Count: 2): O1H2" in caplog.text
    assert "Molecular Comparison Successful" in caplog.text


def test_molecules_information_failed_logging(caplog):
    """测试分子比较失败的日志输出"""
    # 准备测试数据
    molecules = {frozenset([("C", 1), ("H", 4)]): 1, frozenset([("O", 1), ("H", 2)]): 2}
    molecules_flag = False
    initial_info = [{"C": 1, "H": 4}, {"O": 1, "H": 2}]

    # 运行信息输出函数
    with caplog.at_level(logging.INFO):
        molecules_information(molecules, molecules_flag, initial_info)

    # 验证日志输出
    assert "Molecular Comparison Failed" in caplog.text


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--cov=ion_CSP.identify_molecules"])
